services:
  - type: web
    plan: free
    name: Pathan-BOT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Arshlankhan786/Movies_vala_order/tree/main
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
      - key: SHORT_API
        sync: false
      - key: SHORT_URL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - Key: MAX_RIST_BTNS
        sync: false
      - key: CUSTOM_FILE_CAPTION
        sync: false
      - key: SUPPORT_CHAT
        sync: false
      - key: IMDB
        sync: false
      - key: PM_IMDB
        sync: false
